name: pendart
description: A Flutter package for editing and rendering Pendart markup - a lightweight markup language directly converted to Flutter widgets without HTML intermediary
version: 0.3.0
homepage: https://github.com/rp01/pendart

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

repository: https://github.com/rp01/pendart
issue_tracker: https://github.com/rp01/pendart/issues
